Fix: Precommit config was searching nonexistent folder
sign-language-processing/pose-evaluation pull request #9
Opened 2024-12-12 14:34 UTC by cleong110

Very small PR, I discovered the pre-commit config was searching for files in "signwriting", not "pose_evaluation".

2024-12-12 14:51 UTC, AmitMY requested changes

2024-12-12 14:51 UTC, AmitMY commented on .pre-commit-config.yaml
> +  - repo: local
i would have expected you only need to change one line:
```yaml
repos:
  - repo: local
    files: ^ pose_evaluation/
```
(as in, the files are under "repos")

but if you tested it, happy to merge

2024-12-12 16:06 UTC, cleong110 commented on .pre-commit-config.yaml
> +  - repo: local
I did, and pre-commit didn't like that, gave me an unexpected key warning. Apparently the "files" needs to be either 
* at the top-level: https://pre-commit.com/#top_level-files
* in the individual hooks: https://pre-commit.com/#config-files

... but not in the "repos" level. ¯\_(ツ)_/¯

2024-12-13 19:14 UTC, AmitMY commented on .pre-commit-config.yaml
> +  - repo: local
The more i learn!

2024-12-13 19:14 UTC, merged